# Generated by Django 4.2.17 on 2024-12-19 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Annotate',
            new_name='Annotation',
        ),
    ]
